#!/bin/sh
font="dedede"
green="9ece6a"
red="db4b4b"
background="222831"  # Using the background color from your old script

i3lock -n --force-clock -F -B 5 --color=$background -e \
--refresh-rate=1 --line-uses-inside --pointer=default --pass-media-keys --pass-volume-keys --pass-screen-keys \
--inside-color="$green" --ring-color="$green" --insidever-color="$green" --ringver-color="$green" --insidewrong-color="$red" --ringwrong-color="$red" \
--keyhl-color="$green" --separator-color="$green" --bshl-color="$green" \
--time-str="%H:%M" --time-size=140 --time-pos="960:300" --time-font="Roboto mono:style=Bold" --time-color="$font" \
--date-str="%A %d %B" --date-size=45 --date-pos="960:380" --date-font="Roboto mono" --date-color="$font" \
--verif-text="VERIFYING!!!!" --greeter-text="" --wrong-text="WRONG PASSWORD!" --noinput-text="NO INPUT!!" \
--verif-font="Roboto mono:style:Bold"  --greeter-font="Roboto mono:style:Bold" --wrong-font="Roboto mono:style:Bold" \
--verif-size=50 --greeter-size=50 --wrong-size=50 \
--verif-pos="960:540" --greeter-pos="960:600" --wrong-pos="960:540" \
--verif-color="$green" --greeter-color="$font" --wrong-color="$red" \
--bar-indicator --bar-direction=0 --bar-step=10 --bar-max-height=10 --bar-base-width=10 --bar-total-width=1920 --bar-color=00000000 --bar-pos="0:1070"

