[theme]
theme = "space-villain"

[icons]
icons = "material-nf"
#ttf-firacode-nerd (For icons over the lower menu)

[[block]]
block = "custom"
#command = "echo 'Posture Check'"
command = "echo '{\"icon\":\"weather_thunder\",\"state\":\"Good\", \"text\": \"POSTURE CHECK\"}'"
json = true

[[block]]
block = "music"
format = "$icon {$combo.str(max_w:33,rot_interval:0.5) |}"
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "right"
action = "next"
[[block.click]]
button = "middle"
action = "prev"


[[block]]
block = "cpu"
interval = 1
format_alt = " $icon $frequency{ $boost|} "
[block.theme_overrides]
idle_bg = "#74E291"
idle_fg = "#211C6A"


[[block]]
block = "bluetooth"
mac = "30:50:75:FA:CF:59"
format = " $icon $name "
disconnected_format = ""


[[block]]
block = "net"
format = " ^icon_net_down$speed_down.eng(prefix:K) ^icon_net_up$speed_up.eng(prefix:K) "
format_alt = " $icon {$signal_strength $ssid|Wired connection} "
[block.theme_overrides]
idle_bg = "#0B60B0"
idle_fg = "#FBF9F1"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[block.theme_overrides]
idle_bg = "#891652"
idle_fg = "#FFEDD8"


[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 4000
[block.theme_overrides]
idle_bg = "#FCD299"
idle_fg = "#211C6A"
[[block]]
block = "backlight"
missing_format = ""



[[block]]
block = "battery"
format = " $icon $percentage "
interval=2
full_format="$icon 100%"
device = "DisplayDevice"
driver = "upower"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m/%y %R') "
[block.theme_overrides]
idle_bg = "#11111b"
idle_fg = "#a6e3a1"


